// <auto-generated />
using System;
using Lots.Shell.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lots.Shell.Persistence.Migrations
{
    [DbContext(typeof(LotsDbContext))]
    [Migration("20261009175223_AgentRuns")]
    partial class AgentRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lots.Shell.Persistence.RunMessageRecord", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("text");

                    b.HasKey("RunId", "Seq");

                    b.ToTable("run_messages", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("FinalAnswer")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunMessageRecord", b =>
                {
                    b.HasOne("Lots.Shell.Persistence.RunRecord", null)
                        .WithMany("Messages")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunRecord", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
