// <auto-generated />
using System;
using Lots.Shell.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lots.Shell.Persistence.Migrations
{
    [DbContext(typeof(LotsDbContext))]
    [Migration("20261010190725_Schedules")]
    partial class Schedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lots.Shell.Persistence.ApiTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("api_tokens", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ApprovalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RequiredApprovals")
                        .HasColumnType("integer");

                    b.Property<string>("Risk")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolCallId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("RunId", "ToolCallId")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.AuditForwardStateRecord", b =>
                {
                    b.Property<string>("Target")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint");

                    b.HasKey("Target");

                    b.ToTable("audit_forward_state", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BackendAuth")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PrevHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.HasIndex("UserId", "At");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ConfigResourceRecord", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ManagedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Kind", "Name");

                    b.ToTable("config_resources", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ConfigVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManagedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("Kind", "Name", "AppliedAt");

                    b.ToTable("config_versions", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ConflictVoteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConflictId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ConflictId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "At");

                    b.ToTable("conflict_votes", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ConversationAudioRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bytes")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("conversation_audio", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ConversationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SummarizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.KnowledgeConflictRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ResolvedOption")
                        .HasColumnType("text");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("knowledge_conflicts", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SentAt", "NextAttemptAt");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.QuotaOverrideRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ConcurrentRuns")
                        .HasColumnType("integer");

                    b.Property<int?>("RunsPerMinute")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("SpeechSecondsPerDay")
                        .HasColumnType("double precision");

                    b.Property<long?>("TokensPerDay")
                        .HasColumnType("bigint");

                    b.Property<int?>("ToolCallsPerRun")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("quota_overrides", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunMessageRecord", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("text");

                    b.HasKey("RunId", "Seq");

                    b.ToTable("run_messages", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelRequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliverJson")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("FinalAnswer")
                        .HasColumnType("text");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("LeaseUntilMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Partial")
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RetryOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SubjectTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectTokenProtected")
                        .HasColumnType("text");

                    b.Property<bool>("Tainted")
                        .HasColumnType("boolean");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Viewers")
                        .HasColumnType("text");

                    b.Property<bool>("Voice")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunStepRecord", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("text");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Routing")
                        .HasColumnType("text");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.HasKey("RunId", "Seq");

                    b.ToTable("run_steps", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.ScheduleFireRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Name", "DueAt");

                    b.ToTable("schedule_fires", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.UserCredentialRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Server")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AccessTokenProtected")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenProtected")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Server");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.UserProfileRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.UserSettingsRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("AwayUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DelegateTo")
                        .HasColumnType("text");

                    b.Property<int>("Expressiveness")
                        .HasColumnType("integer");

                    b.Property<int>("Formality")
                        .HasColumnType("integer");

                    b.Property<int>("Pace")
                        .HasColumnType("integer");

                    b.Property<int>("Talkativeness")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VoiceConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("VoiceSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("Warmth")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.UserVocabularyRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("user_vocabulary", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.VoiceConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("Seconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Statement")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "At");

                    b.ToTable("voice_consents", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.VoiceUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("AudioSeconds")
                        .HasColumnType("double precision");

                    b.Property<int?>("Characters")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Provider")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId", "At");

                    b.ToTable("voice_usage", (string)null);
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunMessageRecord", b =>
                {
                    b.HasOne("Lots.Shell.Persistence.RunRecord", null)
                        .WithMany("Messages")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunStepRecord", b =>
                {
                    b.HasOne("Lots.Shell.Persistence.RunRecord", null)
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lots.Shell.Persistence.RunRecord", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
