#!/usr/bin/env bash
# The documentation site (#125): MkDocs Material over docs/, run as its official container.
#   scripts/docs.sh build    strict build into out/site (fails on broken links and pages missing from the nav)
#   scripts/docs.sh serve    live preview on http://localhost:8000
#   scripts/docs.sh check    the ADR index is current and the strict build passes (CI)
set -euo pipefail
cd "$(dirname "$0")/.."
export MSYS_NO_PATHCONV=1
IMAGE=squidfunk/mkdocs-material:9.5.49
root=$(if command -v cygpath >/dev/null; then cygpath -m "$PWD"; else echo "$PWD"; fi)

adr_index() { # docs/adr/index.md from the ADR titles and status lines
  python - "$@" <<'PY'
import re, sys
from pathlib import Path
adr = Path("docs/adr")
rows = []
for p in sorted(adr.glob("[0-9][0-9][0-9][0-9]-*.md")):
    lines = p.read_text(encoding="utf-8").splitlines()
    title = re.sub(r"^#\s*\d+\s*[.–-]?\s*", "", lines[0]).strip()
    status = next((l.split(":", 1)[1].strip() for l in lines if l.lower().startswith("status:")), "")
    rows.append(f"| [{p.stem[:4]}]({p.name}) | {title} | {status} |")
text = "# Decisions\n\nArchitecture decision records: the context, the decision and its consequences. Generated by `scripts/docs.sh` from the\nrecords themselves.\n\n| ADR | Decision | Status |\n|---|---|---|\n" + "\n".join(rows) + "\n"
target = adr / "index.md"
if "--check" in sys.argv:
    sys.exit(0 if target.exists() and target.read_text(encoding="utf-8") == text else 1)
target.write_text(text, encoding="utf-8", newline="\n")
PY
}

case "${1:-build}" in
  build) adr_index; docker run --rm -v "$root:/docs" "$IMAGE" build --strict ;;
  serve) adr_index; docker run --rm -it -p 8000:8000 -v "$root:/docs" "$IMAGE" ;;
  check)
    adr_index --check || { echo "docs/adr/index.md is stale: run scripts/docs.sh build" >&2; exit 1; }
    docker run --rm -v "$root:/docs" "$IMAGE" build --strict --quiet
    echo "docs ok"
    ;;
  *) echo "usage: scripts/docs.sh build|serve|check" >&2; exit 2 ;;
esac
