#!/usr/bin/env python
"""Lists the licenses of all NuGet (restored) and npm dependencies and fails on anything that is not
permissive/Apache-2.0-compatible. Run after `dotnet restore` and `npm ci`.

Usage: python scripts/license-check.py [--write docs/third-party-licenses.md]
"""
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NUGET = Path(os.environ.get("NUGET_PACKAGES", Path.home() / ".nuget" / "packages"))

# SPDX ids that are compatible with distributing under Apache-2.0.
ALLOWED = {
    "MIT", "MIT-0", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "0BSD", "Unlicense", "CC0-1.0",
    "BlueOak-1.0.0", "Python-2.0", "Zlib", "PostgreSQL", "MS-PL", "CC-BY-4.0",
}
COPYLEFT = re.compile(r"\b(A?GPL|LGPL|SSPL|BUSL|EUPL|CPAL|OSL)", re.I)

# Packages whose nuspec only has a licenseUrl / no expression, checked by hand against the project's license.
MANUAL = {
    "microsoft.netcore.platforms": "MIT",
    "npgsql": "PostgreSQL",
    "npgsql.entityframeworkcore.postgresql": "PostgreSQL",
}


def nuget_license(pkg_dir: Path) -> str:
    for nuspec in pkg_dir.glob("*.nuspec"):
        root = ET.parse(nuspec).getroot()
        ns = {"n": root.tag.split("}")[0].strip("{")}
        lic = root.find(".//n:metadata/n:license", ns)
        if lic is not None and lic.text:
            return lic.text.strip()
        url = root.find(".//n:metadata/n:licenseUrl", ns)
        if url is not None and url.text:
            u = url.text.lower()
            if "mit" in u:
                return "MIT"
            if "apache" in u:
                return "Apache-2.0"
            if "dotnet.microsoft.com/en-us/dotnet_library_license" in u or "microsoft.com/web/webpi/eula" in u:
                return "MS-EULA"
            return f"see {url.text.strip()}"
    return "UNKNOWN"


def nuget_packages() -> dict:
    found = {}
    for assets in ROOT.glob("src/**/obj/project.assets.json"):  # shipped projects only; test packages are not distributed
        data = json.loads(assets.read_text(encoding="utf-8"))
        for key, lib in data.get("libraries", {}).items():
            if lib.get("type") != "package":
                continue
            name, version = key.split("/")
            found[(name.lower(), version)] = lib.get("path", f"{name.lower()}/{version}")
    return found


def npm_packages() -> dict:
    found = {}
    lock = ROOT / "web" / "package-lock.json"
    if not lock.exists():
        return found
    for path, info in json.loads(lock.read_text(encoding="utf-8")).get("packages", {}).items():
        if not path or info.get("dev"):
            continue  # dev-only tools are not distributed
        pj = ROOT / "web" / path / "package.json"
        lic = "UNKNOWN"
        if pj.exists():
            raw = json.loads(pj.read_text(encoding="utf-8")).get("license", "UNKNOWN")
            lic = raw if isinstance(raw, str) else raw.get("type", "UNKNOWN")
        found[(path.split("node_modules/")[-1], info.get("version", "?"))] = lic
    return found


def ok(expr: str) -> bool:
    if COPYLEFT.search(expr):
        return False
    ids = [t for t in re.split(r"[\s()]+|\bOR\b|\bAND\b", expr) if t and t not in ("OR", "AND")]
    # "A OR B": any permissive alternative is enough. "A AND B": every term must be fine.
    if " OR " in expr:
        return any(i in ALLOWED for i in ids)
    return bool(ids) and all(i in ALLOWED for i in ids)


def main() -> int:
    rows, bad = [], []
    for (name, version), rel in sorted(nuget_packages().items()):
        lic = MANUAL.get(name) or nuget_license(NUGET / rel)
        rows.append(("NuGet", name, version, lic))
        if not ok(lic):
            bad.append(("NuGet", name, version, lic))
    for (name, version), lic in sorted(npm_packages().items()):
        rows.append(("npm", name, version, lic))
        if not ok(lic):
            bad.append(("npm", name, version, lic))

    if "--write" in sys.argv:
        out = Path(sys.argv[sys.argv.index("--write") + 1])
        lines = ["# Third-party licenses", "",
                 "Generated by `python scripts/license-check.py --write docs/third-party-licenses.md`. "
                 "Runtime dependencies of the shipped projects only (test and dev tooling are not distributed).", "",
                 "| Ecosystem | Package | Version | License |", "|---|---|---|---|"]
        lines += [f"| {e} | {n} | {v} | {l} |" for e, n, v, l in rows]
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(rows)} dependencies checked")
    for e, n, v, l in bad:
        print(f"NOT OK: {e} {n} {v}: {l}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
